version: '3'

networks:
  dev:
    driver: bridge

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  postgres:
    restart: always
    networks:
      - dev
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data:
  pgdata: