name: Bug/Crash Report
description: Create a bug or crash report for Centria Hub.
title: "[Bug] <title>"
labels: [bug]

body:
  - type: markdown
    attributes:
      value: "## Describe the bug\nA clear and concise description of what the bug is."

  - type: textarea
    id: bug_description
    attributes:
      label: "Bug Description"
      description: "Provide a clear and concise description of the issue."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Steps to Reproduce"

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the issue."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false

  - type: dropdown
    id: operating_system
    attributes:
      label: "Operating System"
      description: "Select your operating system."
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: "Browser"
      description: "Which browser are you using?"
      placeholder: "e.g. Chrome, Firefox, Safari"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
    validations:
      required: false