blank_issues_enabled: false
contact_links:
  - name: Centria Hub Support Server
    url: https://discord.com/channels/1332330038850359337/1338901771871064084
    about: If you need help regarding Centria Hub, please join our support server!