name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: <title>"
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: "## Feature Description\nProvide a clear and concise description of the feature or improvement."

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "Describe the feature you'd like to see."
      placeholder: "A detailed description of the feature."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this feature needed? What problem does it solve?"
      placeholder: "Explain why this feature would be useful."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "Have you considered any alternative solutions?"
      placeholder: "Describe any alternative solutions you've considered."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other relevant information or screenshots."
    validations:
      required: false